### PR TITLE
3.31.0

### PR DESCRIPTION
**Pull request by markotoplak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by markotoplak** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge-admin rerender

**Comment by carlodri** [comment]
sorry I'm removing myself as maintainer since I'm not able to actively contribute to the feedstock

**Comment by markotoplak** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
