### PR TITLE
Rerender 3.30.2 with conda-smithy

### PR DESCRIPTION
**Pull request by markotoplak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Increased build number
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
Weird. Did you spot any differences in package resolution between mambabuild and conda-build?

It seems to build fine, and then crash :/

**Comment by markotoplak** [comment]
@wolfv, I checked with `diff` and the package plan for the environment is the same.

The new build process seems to do `Reloading output folder: D:\bld` multiple times though and thus does multiple package resolutions. I only see one package resolution in the old build. After the successful build, there is another one for testing. This is unlikely to be related to the failing build though.

**Comment by markotoplak** [comment]
@conda-forge-admin, please rerender

**Comment by markotoplak** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
