### PR TITLE
[WIP] Run tests

### PR DESCRIPTION
**Pull request by PrimozGodec**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
Failing tests:
- [ ] ERROR: test_subclasses (Orange.tests.test_sparse_table.InterfaceTest) fix: https://github.com/biolab/orange3/pull/4747
- [ ] ERROR: test_subclasses (Orange.tests.test_table.InterfaceTest) fix: https://github.com/biolab/orange3/pull/4747
- [ ] FAIL: test_minimum_size (Orange.widgets.data.tests.test_owcontinuize.TestOWContinuize) - height > 700
- [ ] FAIL: test_minimum_size (Orange.widgets.data.tests.test_owimpute.TestOWImpute) height > 700
- [ ] FAIL: test_minimum_size (Orange.widgets.data.tests.test_owpivot.TestOWPivot) height > 700
- [ ] FAIL: test_select_by_click (Orange.widgets.data.tests.test_owpivot.TestOWPivot)
- [ ] FAIL: test_minimum_size (Orange.widgets.evaluate.tests.test_owrocanalysis.TestOWROCAnalysis)  height > 700
- [ ] FAIL: test_nomogram_lr (Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram
- [ ] FAIL: test_nomogram_nb (Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram)

**Comment by markotoplak** [comment]
Closed in favor of #106

**Pull request closed without merging**
